### ISSUE TITLE
Need help running in phonepag

### ISSUE THREAD

**Issue by SamerDiab** [greybax/cordova-plugin-native-spinner#11]
Hello, i am currently trying to import this spinner to phone gap using the phonegap local command, after importing, i included spinner.js in my html, i am a beginner with phone gap, and i have researched me bum off trying to figure this out. 
Any help is appreciated.

**Comment by greybax** [comment]
If you are using Cordova you need to call:

`cordova plugin add cordova-plugin-native-spinner`

For Phonegap:

`phonegap plugin add phonegap-plugin-barcodescanner`


Hope I've answered on your question.

**Comment by SamerDiab** [comment]
I did try to import it and import was succesfull, but my only problem is that i can’t figure out how to use the SpinnerDialog in my javascript file, SpinnerDialog is aalways undefined, although i tried to import the script :/, can you link ke to a sample phonegap app, or steps to propery import the library and use? Thank you.
