### ISSUE TITLE
Please provide screenshots

### ISSUE THREAD

**Issue by guylando** [greybax/cordova-plugin-native-spinner#12]
To decide if we want to use this plugin we must see screenshots of how it looks on android+ios.

**Comment by andreszs** [comment]
Posting screenshots would be misleading, as Google keeps changing the native spinner in every single Android version (maybe not so often in iOS), so whatever screenshot is uploaded it will correspond to a single Android version only.
To see how it works, perform any operation that shows the system's spinner, like searching for mobile networks. That's the spinner and dialog you'll get.

**Comment by guylando** [comment]
I personally believe that it would help more people choose the library to see at least one image of each platform and can add a note that the image might be outdated depending on the OS.
I mean images relevant for some devices are better than no images at all, in getting the general impression for a person not familiar with this.

**Comment by guylando** [comment]
Here is an example of what I speak about which greatly helped me understand that plugin even if the images are outdated and dont represent all the devices in the world:
https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller#2-screenshots

**Comment by narayanncube** [comment]
Doesn't work on android or iOS over inappbrowser. Please help

**Comment by andreszs** [comment]
@narayanncube no Cordova events or methods are directly available from the **InAppBrowser** context.

To send an event from within your InAppBrowser to your Cordova app, you must use the message event from the IAB v3.1.0-dev. Check out the section [Using the message event and postMessage API to close the InAppBrowser](https://www.andreszsogon.com/how-to-close-inappbrowser-window-in-cordova-by-itself/) in that article, and modify it to show the native spinner instead of closing the IAB.

**Comment by 08Thug** [comment]
can we change the color of the spinner!?
If possible could anyone help me with it...

**Comment by greybax** [comment]
@08Thug on the first, spam is not good, isn't it? This question is about screenshots and not about spinner color. At second, you can see the code and read `README.md` the file that this plugin has limited support for the color spinner. You can change only spinner text color and only in iOS. 
So solution could be is to implement this functionality by yourself and maybe send PR to this repo.
